### PR TITLE
Use node to manage the texvcjs versions for mathoid

### PR DESCRIPTION
**Pull request by physikerwelt**
Bug: T135335

### CODE REVIEW

**Comment by gwicke** [comment]
@physikerwelt, would it make sense to ask @cscott about moving the master repo / adding you as a collaborator on npmjs.com? Having two different versions of texvcjs published sounds confusing.

**Comment by physikerwelt** [comment]
@gwicke I started the conversation about that topic on https://phabricator.wikimedia.org/T135335 I think sine there are not too many differences that would work
https://github.com/cscott/texvcjs/compare/master...wikimedia:master

**Comment by gwicke** [comment]
Thank you, @physikerwelt!

**Comment by physikerwelt** [comment]
any updates?

**Comment by physikerwelt** [comment]
@gwicke @cscott @cscott any updates here?

**Comment by d00rman** [comment]
@cscott isn't responding, so I think it's time to just go ahead with this change. @physikerwelt @gwicke any objections?

**Comment by gwicke** [comment]
@d00rman, lets try to catch him on IRC once more? We can actually sort out the repo part quite easily, but for npmjs.com we'll need @cscott.

**Comment by physikerwelt** [comment]
ok. maybe we can search for an intermediate solution. using the masterbranch is shooting at running targets, c.f., https://travis-ci.org/physikerwelt/texvcinfo/jobs/168925378

**Comment by cscott** [comment]
ok, the issue with texvcjs seems to be https://github.com/cscott/texvcjs/pull/2, which was never resolved; instead the wikimedia fork continued to diverge.  As I understand it, mathoid doesn't use texvcjs directly anymore, instead it uses https://github.com/physikerwelt/texvcinfo, which uses the abstract syntax tree of texvcjs and then performs further transformations.

So one solution here is to have `texvcinfo` import the relevant parsing code from `wikimedia/texvcjs` and drop the dependency.  Then mathoid can depend only on `texvcinfo` in npm (https://www.npmjs.com/package/texvcinfo).  That seems like a more sustainable path forward.  Then `texvcinfo` can drop the parts of the texvcjs code which aren't relevant to mathoid, which is better for long-term maintenance.

Texvcjs is a TeX-to-TeX validator.  That's appropriate for the original math extension and for OCG, which use LaTeX as a rendering engine, but not really appropriate for mathoid.

**Comment by gwicke** [comment]
@physikerwelt, is @cscott's proposal workable for you?

**Comment by physikerwelt** [comment]
@gwicke I think it's not optimal, since it will duplicate a lot of code. But of course that's an option.

w.r.t. cscott#2: I would not care too much about spacing in the retro perspective, if there were not the [mhchem](https://phabricator.wikimedia.org/T140217) problems. Moreover, I never went down the road to modify the internal semantics of custom commands, such as `\reals`.

However, in conclusion the most pragmatic thing to me seems to live with the duplicated code. @d00rman what do you think?

**Comment by gwicke** [comment]
> @gwicke I think it's not optimal, since it will duplicate a lot of code. But of course that's an option.

@physikerwelt @cscott, would it be feasible to share the parser portion between both? It seems that the libraries only diverge in how they process the AST.

**Comment by physikerwelt** [comment]
@cscott I looked again at the discussion in cscott#2 but I could not really figure out the problem there. In the end I can live with both solutions `\reals` ->`\mathbb{R}` -> `\mathbb {R}` and  `\reals` ->`\mathbb {R}`.

**Comment by d00rman** [comment]
I'm not thrilled with the prospect of copy/pasta code, but how about we do just that for the time being and then try to disentangle the small differences in order to be able to isolate the shared code into a library?

**Comment by physikerwelt** [comment]
@d00rman I'm about to continue developing on mathoid and related projects. I still think creating the temporary npm package would be better than just c&p the code. Otherwise I'm afraid that we will never be able to remerge the changes.

**Comment by d00rman** [comment]
kk @physikerwelt let's move on this and not make it a blocker.

**Comment by d00rman** [comment]
Published as [v0.3.2](https://github.com/wikimedia/texvcjs/tree/v0.3.2)

**Pull request merged**
