### PR TITLE
Dev dep

### PR DESCRIPTION
**Pull request by physikerwelt**

### CODE REVIEW

**Comment by physikerwelt** [comment]
@dmajda the generated code in pegjs0.10 looks much cleaner compared to pegjs.0.9. However, now there are different jshint problems. Is there any best practice advise to deal with jshint and the pegjs generated files?

**Comment by d00rman** [comment]
@physikerwelt since this is a generate file, I think the easiest way to go about it is to simply ignore it, as you've done.

**Comment by dmajda** [comment]
> Is there any best practice advise to deal with jshint and the pegjs generated files?

Don’t lint them :-)

While I strive for generated files to be very clean JavaScript, people use different linters and different configurations and it’s obviously impossible to make generated files pass with all of them, so linting these files will always be problematic. Of course, not linting generated files means not linting the action/predicate/initializer code, but this is usually not a big deal as it is typically small and straightforward.

An ideal solution would be a linter plugin that would allow one to lint the code in grammars directly. I looked at [ESLint’s plugin documentation](http://eslint.org/docs/developer-guide/working-with-plugins) and it looks doable, so I [called for action](https://twitter.com/peg_js/status/786190910291709952). Let’s see if someone implements it.

All that said, I’ll accept patches for unnecessary linter rule violations, as long as they don’t conflict with something more important.

**Comment by physikerwelt** [comment]
ok. It seems that we all agree. So the patch is ready for code review.

**Pull request merged**
