### PR TITLE
Add missing integrals

### PR DESCRIPTION
**Pull request by ClaudeZou**
Added different types of integrals as requested by @physikerwelt

### CODE REVIEW

**Comment by physikerwelt** [comment]
Maybe it's better to wait with the merge until the mathml rendering mode gets default.

**Comment by d00rman** [comment]
Any special reason for it?

**Comment by physikerwelt** [comment]
Yes. It's not compatible to the old version of texvc.
```
~/texvc$ ./texvc /tmp /tmp '\oint'
+058bf10c50ba4ee074da24c60a590314
~/texvc$ ./texvc /tmp /tmp '\oiint'
F\oiint
```
So this is where the divergence would start.

**Comment by physikerwelt** [comment]
@d00rman one option to keep track of those additions would be to add an fake package for example `mathoid` for that purpose.

**Comment by d00rman** [comment]
> @d00rman one option to keep track of those additions would be to add an fake package for example mathoid for that purpose.

:+1:

**Comment by physikerwelt** [comment]
@ClaudeZou can you create such a package and add the new commands to that package?

**Comment by physikerwelt** [comment]
:+1: I'll rebase and merge now

**Pull request merged**
