### PR TITLE
Fix upstream typo: \hAar -> \hArr

### PR DESCRIPTION
**Pull request by physikerwelt**

### CODE REVIEW

**Comment by d00rman** [comment]
Why `\hArr` ? texvc distinguishes only between `\harr` and `\Harr` [according to its manual](http://tug.ctan.org/tex-archive/macros/latex/contrib/texvc/texvc.pdf)

**Comment by physikerwelt** [comment]
@d00rman \hAar was a typo and supposed to be \hArr the manual was generated from the wrong source;-)

**Comment by d00rman** [comment]
@physikerwelt I'm talking about `\hArr` vs `\hHarr`. `\hAar` is obviously a typo, but there's no reference to `\hArr` either...

**Comment by physikerwelt** [comment]
@d00rman I don't understand what you mean by reference.

**Comment by d00rman** [comment]
> I don't understand what you mean by reference.

According to `texvc`'s manual, it understands only `\harr` and `\Harr`, but not `\hArr`, so my question is why aren't we using those?

**Comment by physikerwelt** [comment]
@d00rman I might have removed `\hArr` from the manual, because I consider as as useless.

I think the rationality of @cscott was
texvc had
` | "\\hAar" -> LITERAL (HTMLABLE (FONT_UF, "\\Leftrightarrow ", "&hArr;"))`
https://github.com/wikimedia/mediawiki-extensions-Math/blob/a55de558641c100f80c071025bbc290c814e49ff/math/texutil.ml#L215
but the html element is &hArr; so introduce a new macros called `\hArr`.

**Comment by d00rman** [comment]
Ah, ok! thnx for the explanation @physikerwelt

**Pull request merged**
