### PR TITLE
Add support for italic capital Greek letters

### PR DESCRIPTION
**Pull request by mormegil-cz**
There is currently no way to write a bold italic capital Greek letter (e.g. for angular velocity vector).

The easiest way to achieve this in Math/MathJax is to use `\boldsymbol \varOmega` which is already supported by MathJax, but it is not recognized by texvc, so it is rejected.

This commit adds all symbols for capital Greek variables (`varDelta`, `\varOmega`, ...) supported by MathJax (see https://docs.mathjax.org/en/latest/tex.html#v) to the list of supported macros.

### CODE REVIEW

**Comment by physikerwelt** [comment]
Thank you for the pull request. However, there are two issues.
1) We need test cases
2) This is a change in syntax. Therefore it needs community support. You can ask this group https://phabricator.wikimedia.org/T195861 for feedback

**Comment by physikerwelt** [comment]
I think it would also be a good idea to have some visual tests before we deploy this.

Currently, we have 92 visual test cases at
https://github.com/wikimedia/mathoid/blob/master/test/files/mathjax-texvc/test.md
these tests are automatically generated via
https://github.com/wikimedia/mathoid/blob/master/scripts/imgUpdate.js
to generate these test cases you'll have to overwrite the dependency to texvcjs here
https://github.com/wikimedia/mathoid/blob/master/package.json#L41

Let me know if you run into trouble... documentation is really a problem.

**Comment by mormegil-cz** [comment]
Submitted patch to add tests: https://gerrit.wikimedia.org/r/c/mediawiki/services/mathoid/+/514785

**Comment by physikerwelt** [comment]
>     2\. This is a change in syntax. Therefore it needs community support. You can ask this group https://phabricator.wikimedia.org/T195861 for feedback

I did that via http://openmath.org/pipermail/wiki-l/2019-August/000000.html

**Comment by d00rman** [comment]
> @d00rman how do we proceed here. Should I just release a new texvcjs version to npm?

Yup, but there is no version bump in this PR. @mormegil-cz could you bump the version in package.json to 0.3.7 please?

**Comment by physikerwelt** [comment]
@mormegil-cz this is now on npm however, the [gerrit change](https://gerrit.wikimedia.org/r/#/c/mediawiki/services/mathoid/+/514785/) needs to point to the latest texvcinfo version, which is [0.5.4](https://github.com/wikimedia/texvcinfo/commit/e099831df45cd54a71f8c3fcb075f8175e353181#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R3).

**Pull request merged**
