### PR TITLE
Remove litsq syntax rules

### PR DESCRIPTION
**Pull request by golopot**
Syntax is simplified without changing extensional behavior.

### CODE REVIEW

**Comment by physikerwelt** [comment]
@q4w56 can you make the commit more verbose, so that it's clear why the behavior is not changed. How was the situation before your change and how will the situation be after your change. Currently, I can not judge, if your change really does not change anything.

**Comment by q4w56** [comment]
@physikerwelt I don't know why, I just try and error and make it pass the test.

**Comment by physikerwelt** [comment]
@q4w56 but we don't know if the tests test all cases. Currently the code coverage reports, do not include the generated code. So there is a chance that you missed a case. This should be avoided, since it will cause that some formulae on Wikipedia look different or fail to render. So please understand that we must be very careful and understand the consequences of every change in detail.

**Comment by q4w56** [comment]
It is very hard and time consuming to argue that the two grammars are equivalent. The more practical way is to add more tests cases and believe the test.

**Comment by q4w56** [comment]
Btw I found that `\sqrt[5]` is accepted and converted to `+{\sqrt {[}}5]`, though it is rejected by mathjax and my local Tex editor.

**Comment by physikerwelt** [comment]
Update. I am about to develop an integration test that check this PR against all current formulae. I'll check this PR on Sat 20.1.18

**Comment by golopot** [comment]
I have done rebasing.

**Comment by physikerwelt** [comment]
thanks... i'm still working on the verification, though

**Pull request closed without merging**
