### PR TITLE
Accept and convert whitelisted unicode

### PR DESCRIPTION
**Pull request by golopot**
Accept and convert whitelisted unicode characters

"∫ ∂ τ" is converted to "\int \partial \tau ".

This feature can be disabled by passing the option "no_unicode_aliase".

See: https://phabricator.wikimedia.org/T165751

### CODE REVIEW

**Comment by physikerwelt** [comment]
@q4w56 thank you for your contribution. This is definitely a very good start.

**Comment by q4w56** [comment]
Any idea on what's left to do?

**Comment by physikerwelt** [comment]
This is certainly blocked on the removal of the PNG rendering mode. cf. https://phabricator.wikimedia.org/T74240

**Comment by q4w56** [comment]
Why is it blocked by T74240?

**Comment by physikerwelt** [comment]
Latex would not process these macros. And LaTeX does not process the checked tex but the original since the checking process is not idempotent.

**Comment by golopot** [comment]
Should the unicode feature be enabled by default or disabled by default?

**Pull request closed without merging**
